import forLoop from './for';
import forEach from './foreach';
import projectArr from './project';
import projectMap from './map';
import forEachFitlerArray from './foreach-filter';
import filterMapChain from './filter-map-chain';
import queryingTrees from './querying-trees';
// import mapConcatAllQuery from './querying-map-concatall';
// import mapConcatAllQueryDeep from './querying-map-concatall-deep';
// import concatMapQuery from './querying-with-concatmap';
// import reducingArrays from './reducing-arrays';
import reducingArraysWithPrototype from './reducing-arrays-with-prototype';
import reduceIntro from './reduce-intro';
import reduceArrToObject from './reduce-array-to-object';
import { reduceDoubler, reduceMapDoubler } from './reduce-common-patterns';

export const arrForLoop = forLoop;
export const arrForEach = forEach;
export const arrProjectArr = projectArr;
export const arrProjectMap = projectMap;
export const arrForEachFilter = forEachFitlerArray;
export const arrFilterMapChain = filterMapChain;
export const arrQueryingTrees = queryingTrees;
// export const arrMapConcatAllQuery = mapConcatAllQuery;
// export const arrMapConcatAllQueryDeep = mapConcatAllQueryDeep;
// export const arrConcatMapQuery = concatMapQuery;
// export const arrReducing = reducingArrays;
export const arrReducingWithPrototype = reducingArraysWithPrototype;
export const arrReduceIntro = reduceIntro;
export const arrReduceArrToObject = reduceArrToObject;
export const arrReduceDoubler = reduceDoubler;
export const arrReduceMapDoubler = reduceMapDoubler;

